# This workflow is used to build the extension and publish it as a GitHub release

name: Release

on:
  # Triggers the workflow on push of version tag
  push:
    tags:
      - "v*.*.*.*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          npm install
          npm run build
          
      - name: Generate documenation
        run: |
          npm run generateIconReferences
          
      - name: Build assets for release
        run: |
          tar cvf Explorer.novaextension.tar Explorer.novaextension

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: Explorer.novaextension.tar
